
services:
  server:
    build: .
#    command: python3 ./app/main.py
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
 db-data:
